rtf = new RTFDocument()
rtf.add_font('Courier')
rtf.add_font('Serif')
rtf.add_color('black',0,0,0)
rtf.add_color('red',255,0,0)
rtf.add_color('green',0,255,0)
rtf.add_color('blue',0,0,255)

rtf.set_font('Serif')
rtf.set_font_size(20)
rtf.center()
rtf.text('Title #1')
rtf.set_font('Courier')
rtf.set_font_size(12)
rtf.paragraph()
rtf.justify()
rtf.text('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis quis rutrum turpis. Vivamus consectetur eget dui vitae placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin vitae tristique lorem, faucibus rhoncus felis. Nunc velit purus, aliquam sit amet posuere sed, maximus quis velit. Aliquam sapien sapien, pulvinar sed rhoncus non, ultrices quis ligula. Ut vitae tortor sed velit ultricies mattis. Donec aliquet lacus nec purus luctus, ut tempor velit convallis. Morbi euismod molestie magna, sit amet accumsan purus laoreet sed. Donec elementum egestas eros eget tincidunt. Suspendisse tincidunt nulla ac ante porta tempus.')
rtf.paragraph()
rtf.left()
rtf.text('Curabitur ac velit elit. Nunc consequat, velit a imperdiet accumsan, ante arcu pellentesque quam, id porttitor magna tellus sit amet tortor. Quisque non efficitur nunc. Pellentesque viverra justo quis nulla gravida dapibus. Etiam augue massa, commodo vel consectetur vitae, accumsan eu augue. Cras ac elit sed mi fringilla pharetra a sit amet dui. Aliquam venenatis lobortis eleifend. Aenean suscipit ipsum massa, et viverra quam fringilla ac. Cras ullamcorper consectetur neque, vitae dignissim ex ornare vitae. Nulla ipsum justo, tincidunt nec volutpat non, pharetra in tellus. Aenean mollis risus vitae semper efficitur. Integer pulvinar mi tellus, vel pretium lorem accumsan vitae.')
rtf.paragraph()
rtf.right()
rtf.text('Nulla nec condimentum libero, vitae tincidunt libero. Nulla placerat, felis id bibendum volutpat, dui nisi mollis nisl, ac tristique neque risus ac nulla. Vestibulum dignissim, elit in blandit aliquet, enim nibh cursus turpis, sed posuere risus quam lacinia massa. Etiam interdum commodo euismod. Vivamus lacinia, urna at finibus molestie, felis diam feugiat diam, a scelerisque dui nunc ut mi. Nulla vestibulum orci velit, lacinia fermentum velit sagittis eget. Donec dolor sem, maximus suscipit feugiat eget, fringilla nec ipsum. Donec at purus facilisis, interdum purus condimentum, facilisis urna. Suspendisse potenti. Suspendisse eu mi vitae lacus scelerisque aliquam. Nunc pellentesque ultricies lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis tincidunt velit ac mauris posuere feugiat. Sed quis ipsum vitae purus facilisis fringilla nec eu arcu. Vestibulum nunc ligula, interdum eget purus vitae, accumsan luctus sem. Maecenas fringilla mi rhoncus pellentesque rutrum.')
rtf.paragraph()
rtf.center()
rtf.text('Nunc metus elit, dictum vel velit nec, commodo maximus est. In blandit sapien sapien, vitae gravida arcu venenatis sit amet. Nulla dignissim justo nec urna sagittis, vel viverra arcu pellentesque. Donec sit amet gravida ante. Morbi a massa non ex rhoncus condimentum. Aliquam condimentum molestie dapibus. Nullam a dui et nunc mattis feugiat at sed augue. Donec convallis turpis justo, nec commodo turpis sodales a. Morbi sed sapien ut orci tempor vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis suscipit est vulputate eleifend.')
console.log rtf.save()

